name: PRODUCTION -- Build & Push Docker Image
on:
  push:
    branches: [main]
    paths:
      - "**"

jobs:
  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: lukasdeco/indexer

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: themetadao/asset-watcher:main
          labels: ${{ steps.meta.outputs.labels }}

  redeploy_app:
    name: Redeploy app on Railway
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Call Redeploy API
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo railway toke: $RAILWAY_TOKEN
          echo "Authorization: Bearer ${RAILWAY_TOKEN}"
          curl https://backboard.railway.app/graphql/v2 \
          -X POST \
          -H "Authorization: Bearer ${RAILWAY_TOKEN}" \
          -H "Content-Type: application/json" \
          --data '{"query": "mutation serviceInstanceDeploy($serviceId: String!, $environmentId: String!) {\n  serviceInstanceDeploy(serviceId: $serviceId, environmentId: $environmentId)\n}\n", "variables": { "environmentId": "0942e3fe-8ec3-49b4-b8fb-26eb10b6e08f", "serviceId": "bb01c469-2d71-42f1-ac50-02252f7d1669" } }' 
